spring.application.name=backend

spring.mongodb.uri=${SPRING_MONGODB_URI}

jwt.secret=${JWT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.main.lazy-initialization=true

aws.s3.bucket=${AWS_S3_BUCKET:your-bucket-name}
aws.s3.region=${AWS_REGION:us-east-1}