spring.application.name=backend

spring.mongodb.uri=mongodb+srv://Thuan:12112004@cluster0.ka590mv.mongodb.net/food-delivery?appName=Cluster0

jwt.secret=my_super_secret_key_for_jwt_signing_2024

upload.dir=uploads/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB